source 'https://github.com/CocoaPods/Specs.git'

target 'JAQDiceView', :exclusive => true do
  pod "JAQDiceView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JAQDiceView", :path => "../"

  
end
